"""Add completed field to cards

Revision ID: 53de6e6346a2
Revises: 1d9ab05718e2
Create Date: 2025-05-08 11:32:43.197754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53de6e6346a2'
down_revision: Union[str, None] = '1d9ab05718e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('completed', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'completed')
    # ### end Alembic commands ###
