"""new logic

Revision ID: 6e2c703032c1
Revises: 1123b5d02485
Create Date: 2025-05-17 15:41:50.987602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2c703032c1'
down_revision: Union[str, None] = '1123b5d02485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('tags', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'color')
    op.drop_column('cards', 'is_archived')
    # ### end Alembic commands ###
